# Generated by Django 4.0.6 on 2022-10-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0004_rename_city_course_rename_country_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='materials',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='purpose',
            field=models.CharField(choices=[('Enquiry', 'Enquiry'), ('Place order', 'Place order'), ('Return', 'Return')], max_length=200),
        ),
    ]
