# Generated by Django 4.0.6 on 2022-10-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0005_alter_person_materials_alter_person_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='materials',
            field=models.CharField(max_length=250),
        ),
    ]
